### ISSUE TITLE
exception creating a new doc

### ISSUE THREAD

**Issue by DeepDiver1975** [tomneedham/oc-drawio#2]
```
{"reqId":"s66c5ekAVwme2FLWsHRI","level":3,"time":"2018-08-14T07:37:02+00:00","remoteAddr":"46.183.103.17","user":"deepdiver","app":"index","method":"GET","url":"\/apps\/drawio\/editor\/53671","message":"Exception: {\"Exception\":\"OCP\\\\AppFramework\\\\QueryException\",\"Message\":\"Could not resolve OCA\\\\Drawio\\\\Controller\\\\PageController! Class OCA\\\\Drawio\\\\Controller\\\\string does not exist or error resolving constructor arguments: Could not resolve PageController! Class PageController does not exist\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/Routing\\\/RouteActionHandler.php(46): OC\\\\AppFramework\\\\App::main('PageController', 'editor', Object(OC\\\\AppFramework\\\\DependencyInjection\\\\DIContainer), Array)\\n#1 [internal function]: OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler->__invoke(Array)\\n#2 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/Route\\\/Router.php(342): call_user_func(Object(OC\\\\AppFramework\\\\Routing\\\\RouteActionHandler), Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/base.php(915): OC\\\\Route\\\\Router->match('\\\/apps\\\/drawio\\\/ed...')\\n#4 \\\/var\\\/www\\\/owncloud\\\/index.php(54): OC::handleRequest()\\n#5 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/AppFramework\\\/App.php\",\"Line\":86}"}

**Comment by DeepDiver1975** [comment]
https://doc.owncloud.org/server/8.0/developer_manual/app/info.html

**Comment by DeepDiver1975** [comment]
fixed - thx
